# Examining Characteristics of the Logistic Equation Using Python

## 1. Introduction
As seen in *The Fundamental Dynamics Formula*, the simplest first order linear ordinary differential equation (ODE) can be given by 
$$ \frac{dP}{dt} = kP  \tag{1.1}$$
where our solution is the function $P(t) = P_0e^{kt}$. This equation is often used to model population growth. As it is exponential, the model in question will either decay when $k < 0$ or grow e Pponentially when $k > 0$. 

However most models will not grow or decay exponentially, and thus have a carrying capacity, $M$. Under the assumptions that:

- $\frac{dP}{dt} \approx kP $ if $P$ is small
 
- $\frac{dP}{dt} < 0 $ if $P > M$

  
The equation that incorporates these assumptions is the Logistic Equation:
$$ \frac{dP}{dt} = kP(1 - P) \tag{1.2}$$
with our solution:
$$ P(t) = \frac{1}{1 + e^{-kt}}   \tag{1.3}$$

In *Simple Mathematical Models With Very Complicated Dynamics* by Robert May, this is how the Logistic ODE is defined as,
Using Euler's Method, we can rewrite the Logistic Equation (1.2) as follows:
$$  P_{n+1} =  aP_n(1- P_n) \tag{1.4}$$
May calls this equation "the simplest nonlinear difference equation." While simple, May also explains how $P$ must remain on the domain (0,1). Outside of these bounds, the iterations diverege towards $-\infty$. Furthermore, May requires that $1 < a < 4$. When this inequalty is false, the function begins to behave chaotically and, in the context of $P =$ population, the population becomes extinct. 

These findings are similar to those found by Edward N. Lorenz in *The Problem of Deducing the Climate from the Governing Equations*. To describe the behavior of $P$, Lorenz calculates the roots of Eq(1.7) and derives
$$ P = 0, a-1, \frac{a+1}{2}+\sqrt{a+1}, \frac{a+1}{2}-\sqrt{a+1} \tag{1.5}$$

Lorenz states that all of these roots are real when $0 \leq a \leq 3$. However for $3 < a \leq 4$, only the roots $P = 0, a-1$ are real. This leads to $P$ being unstable and in the context unstable climates.

The behavior of this solution, described as the Logstic Map, is dependent of $a$. According to the Logistic Map Wikipedia, is as follows:

- $0 < a < 1$: The population will eventually die regardless of $P_0$
- $1 < a < 2$: The population will approach the value $\frac{a-1}{a}$
- $2 < a < 3$: The population will approach the value $\frac{a-1}{a}$, but will fluctuate around this value
- $3 < a < 3.44949$: The population will approach permanent oscillations between the values $\frac{1}{2a}(a+1\pm\sqrt{(a-3)(a+1)})$
- $3.44949 < a < 3.54409$: The population will approach permanent oscialltions between four values
- $3.54409 < a $: The population will approach oscillations between 8, 16, 32,... values

The characteristics shown in *Simple Mathematical Models With Very Complicated Dynamics* by Robert May, *The Problem of Deducing the Climate from the Governing Equations* by Edward Lorenz, and Logistic Map Wikipedia connect to the coursework completed in Math340. In this report we will review the follwing concepts and how they are explored in the corresponding homework assignments. 
- The simplest ODE (HW 5)
- Using Finite Difference Methods to solve ODEs (HW 9)
- The simplest ODE and its connection to the Fibonacci Sequence (HW 9)
- Solutions of the Logistic Equation using symbolic compuring (HW 10)
- Numerical solutions of the Logistic Map (HW 10)
- The Sigmoid function (HW 3)
- The Softmax function (HW 5)

## 2. Methodology



### 2.1 Solving Linear First Order Differential Equations
The simple ODE given by Eq(1.1) can be solved using analytical and numerical approximation approaches. While there are many analytical methods of solving this differential equation, we will demonstrate how to solve it using seperation of variables. 

#### 2.1.1 Analytical Solution using Seperation of Variables
Given Eq(1.10, begin by multiplying both sides by $\frac{dt}{y}$ 
$$ \frac{dP}{dt} \cdot \frac{dt}{P} = kP \cdot \frac{dt}{P}   \tag{2.1}$$

After simplifying:
$$ \frac {dP}{P} = k dt   \tag{2.2}$$

Integrate both sides:
$$ \int_{P_0}^{P}\frac{dP}{P} = k\int_{0}^{t}   \tag{2.3}dt$$

After integrating, the left hand side is:
$$ ln(P) - ln(P_0) = ln\left(\frac{P}{P_0}\right)   \tag{2.4}$$
and the right hand side is:
$$k(t-0) = k t   \tag{2.5}$$
thus,
$$ ln\left(\frac{P}{P_0}\right) = k t   \tag{2.6}$$

Exponentiating both sides to cancel out $ln$ term:
$$ e^{ln\left(\frac{P}{P_0}\right)} = e^{k t}   \tag{2.7}$$
and simplifying gives us the analytical solution: 

$$ P(t) = P_0e^{k t}   \tag{2.8} $$

#### 2.1.2 Finite Difference Schemes (Euler)
To approximate numerical solutions to ODEs, we can use Finite Difference Methods. The Finite Difference Methods can be expressed using three different schemes
- Forward Difference: $$ \frac{f_{j+1} - f_j}{\Delta t}   \tag{2.9}$$
 
- Backward Difference: $$ \frac{f_j - f_{j-1}}{\Delta t}   \tag{2.10}$$

- Centered Difference: $$ \frac{f_{j+1} - f_{j-1}}{2 \Delta t}   \tag{2.11}$$

The Forward Difference scheme shown above is also refererred to as Euler's Method, or Forward Euler's Method . We will use Euler's method to find the solution to the ODE in Eq(1.1).

Given Eq(1.1), we can rewrite using the Euler Method
$$\frac{P_{j+1} - P_j}{\Delta t} = P   \tag{2.12}$$
Multiplying both sides by $\Delta t$,
$$P_{j+1} - P_j = \Delta t P   \tag{2.13}$$
and isolating $P_{j+1}$,
$$P_{j+1}  =  P_j + \Delta t P   \tag{2.14}$$
To find the numerical solution to this equation, we can compute and plot our solutions using Python.

#### 2.1.3 Fibonacci Sequence as a Solution to Linear ODE
Additonally, we can use the Centered Difference Scheme to show the connection between Eq(1.1) and the Fibonacci Sequence 
$$Z_{n+1} = Z_n + Z_{n-1}   \tag{2.15}$$

Redefining Eq(1) as $ \frac{dZ}{dt} = \sigma Z $, 
$$\frac{Z_{n+1}- Z_{n-1}}{2 \Delta t} = \sigma Z_n   \tag{2.16}$$

Isolating $Z_{n+1}$,
$$ Z_{n+1} = Z_{n-1} + 2 \sigma \Delta t Z   \tag{2.17}$$

Thus for $ \sigma = \frac{1}{2 \Delta t} $, we get the solution:

$$ Z_{n+1} = Z_{n-1} + Z_n   \tag{2.18}$$

Which is our equation for the Fibonacci Sequences

### 2.2 The Logistic Equation

As we described above in Eq(1.2), the Logistic Equation is defined as:
$$ \frac{dP}{dt} = kP\left(1 - \frac{P}{M}\right) $$
Similar to Eq(1.1), this equation can be solved using both analytical and numerical methods. 

#### 2.2.1 Solutions of the Logistic Equation Using Symbolic Computing
Explored in HW10, the analytical solution to the Logistic equation can be derived using symbolic computing. Using Python packages ``scipy``, ``numpy``, and ``matplotlib``, we can obtain our solution and visualize it.

```python
import sympy as sp
import numpy as np
import matplotlib.pyplot as plt

#Define function P, dependent variable t, and constant k
t, k = sp.symbols('t, k')
P = sp.Function('P')

#Define (1) 
eq1 = sp.Eq(sp.Derivative(P(t), t), k*P(t)*(1 - P(t)))
#Use dsolve to obtain solution
sol1 = sp.dsolve(eq1, P(t)) # Without initial condition

display(sol1)
```
$P{\left(t \right)} = \frac{1}{C_{1} e^{- k t} + 1}$

#### 2.2.2 Solutions of the Logistic Equation Using Finite Difference
From HW10, we dervied the numerical approximation of the Logistic equation using finite difference schemes

Using Euler's Method, we can rewrite the Logistic Equation (1.2) as follows:
$$ \frac{P_{n+1}-P_n}{\Delta t} = kP_n(1 - P_n) \tag{2.19}$$

Isolating the left hand side,

$$  P_{n+1}- P_n = \Delta tk  P_n(1- P_n) \tag{2.20}$$

then isolating the $  P_{n+1} $ term

$$  P_{n+1} =  P_n + (\Delta tk)P_n(1- P_n) = P_n(1 + \Delta tk)(1- P_n) \tag{2.21}$$

and for $a = (1 + \Delta tk)$,

$$  P_{n+1} =  aP_n(1- P_n) \tag{2.22}$$

#### 2.2.3 Continuous and Discrete Verisons of the Logistic Map

We explored the concepts described by May and Lorenz in HW10. Using the form of Eq(1.4), we calculated the numerical approximation of the Logistic map and plotted our results for different values of $a$.
```python
#Define initial conditions and parameters
P0 = 0.1
a = [1.8, 2.0, 2.5, 3.5, 3.8, 4.0]

#For iteration
Pvals = []
tVals = []

#Define X and t using different values of sigdt
for i in a:
    t = np.arange(0, 40+i, i)
    P = np.zeros(len(t))
    P[0] = P0
    #Euler method calculation
    for n in range(0,len(P)-1):
        P[n+1] = P[n] + i*P[n]*(1-P[n])
    #Add t-X values to iteration lists
    Pvals.append(P)
    tVals.append(t)

plt.figure(figsize=(9,6))
for i in range(0, len(Pvals)):
    plt.subplot(2,3,i+1)
    plt.plot(tVals[i], Pvals[i], label=f'{a[i]}')
    plt.legend()
    plt.grid()

plt.tight_layout()
plt.show()
```

Our results in these graphs support the claims made by May and Lorenz, that $P$ begins to behave chaotically as $a \to 4$

### 2.3 Sigmoid and Softmax Functions

The following concepts are explored in HW3 and HW5 respectively.

#### 2.3.1 Sigmoid Function
The solution given by Eq(1.4) goes by another name other than the Logistic function. This function also goes by the Sigmoid function, denoted
$$ \sigma = \frac{1}{1+e^{-t}} \tag{2.23}$$
As we can see this function is equivalent to Eq(1.4), for $P_0 = 1$

```python
def sig(x):
    return 1/(1+np.exp(-x))

r1 = np.linspace(0,5,100)
r2 = np.linspace(-5,5,100)
title1 = r'Graph of $\sigma$ = $\frac{1}{1+e^{-x}}$'
plt.title(title1, size=10)
plt.plot(r1, sig(r1))
plt.grid()
plt.show()
```

#### 2.3.2 Softmax Function
The Softmax function is an activation function that similar to the Sigmoid function. Described as an extension of the Sigmoid function, it entends to multi-class problems. 
Given $x = (x_{1}, x_{2}, ..., x_{K})$:
$$ \sigma(x)_{i} = \frac {e^{x_{i}}}{\sum_{j=1}^{K} e^{x_{j}}} \tag{2.24}$$

The following python code defines two methods of calculating the Softmax function and compares its output
```python
def softmax(x):
    exp_x = np.exp(x)
    return exp_x/exp_x.sum()

def softmax_loop(x):
    #Create array same length as x
    sigma = np.arange(0.0,len(x))
    #Sum variable
    exp_sum = 0
    for i in range(0, len(x)):
        #Find e^x_i
        exp_x = np.exp(x[i])
        #Add e^x_i to sum 
        exp_sum += exp_x
        #Store sigma(x)_i
        sigma[i] = exp_x/exp_sum
    return sigma
    
#Example input vector
input_vector = np.array([10, 2.0, 0.1])

#Applying softmax
output_vector = softmax(input_vector)
output_vector2 = softmax_loop(input_vector)
#Displaying results
print("Input Vector:", input_vector)
print("Softmax Output:\n", output_vector)
print('Softmax_loop Output:\n', output_vector2)
#Compare values
print('Difference of Softmax and Softmax_loop functions for each value of x:\n', (output_vector2-output_vector))
```
```
Input Vector: 
[10.   2.   0.1]

Softmax Output: 
[9.99614511e-01 3.35333311e-04 5.01553403e-05]

Softmax_loop Output:
 [1.00000000e+00 3.35350130e-04 5.01553403e-05]

Difference of Softmax and Softmax_loop functions for each value of x:
 [3.85488651e-04 1.68195999e-08 0.00000000e+00]

```

## 3. Results and Discussions

Referencing section 2.1.2, this Python code demonstrates the effectiveness of the Euler method in approximating the solution to Eq(1.1)
```python
import numpy as np
import matplotlib.pyplot as plt

#Define parameters
dt = 0.001
t = np.arange(0,10+dt,dt)
sigma = 0.2
y0 = 0.01
#Create function array that is same size as domain
y = np.zeros(len(t)) #Will add correct values
#Initial condition
y[0] = y0

#Calculate values of y using Euler method
for i in range(0, len(y)-1):
    #Approximation formula
    y[i+1] = y[i] + dt*(sigma*y[i])

#Generate plot
plt.plot(t, y, 'k', linewidth=3)
plt.plot(t, y0*np.exp(sigma*t), '--', color='orange')
plt.legend(['Numerical Solution', 'Analytical Solution'])
plt.title(r'Numerical and Analytical Solution for DE: $\frac{dy}{dt} = \sigma t$')
plt.ylabel('y(t)')
plt.xlabel('t')
plt.grid()
plt.show()
``` 

![Euler-ODE.png](Euler-ODE.png)

As you can see, the numerical solution and analytical solution are approximately the same.


This plot belongs to the code given in section 2.2.3. As we can see, this visualization follows the behavior described by the Logistic Map Wikipedia page. 

![Logistic-Map-Panel-Plot](Logistic-Map-Panel-Plot.png)

This graph below is corresponds to 2.3.1
![sigmoid](sigmoid.png)
From this graph we can see how the solution of the Logistic Equation behaves over the interval [0,5]

## 4. Conclusion

The information given by Robert May in *Simple Mathematical Models With Very Complicated Dynamics* and *The Problem of Deducing the Climate from the Governing Equations* by Edward Lorenz, as well as the Logistic Map Wikipedia are extremely helpful in understanding the characteristics of the Logistic Equation. In addition to reviewing these literature, over the course of the semester these same characteristics were explored in homework assignments in the Math340 course. Topics covered included The Simplest ODE, Using Finite Difference Methods to solve ODEs, The simplest ODE and its connection to the Fibonacci Sequence, Solutions of the Logistic Equation using symbolic compuring, Numerical solutions of the Logistic Map, he Sigmoid function and The Softmax function. In covering these topics, I have gained valuable exerience in modeling, compuation, and visualization that I hope will allow me to pursue a career in Data Analytics. 

### Author Contributions
Introduction, V.V.; Methodology, V.V; Results and Discussions, V.V; writing—original draft preparation, V.V; writing—review and editing, V.V\
All authors have read and agreed to the published version of the manuscript.

### Appendices

In [ ]:
"""Python Code used above"""
#General import statements
import sympy as sp
import numpy as np
import matplotlib.pyplot as plt

#Define function P, dependent variable t, and constant k
t, k = sp.symbols('t, k')
P = sp.Function('P')

#Define (1) 
eq1 = sp.Eq(sp.Derivative(P(t), t), k*P(t)*(1 - P(t)))
#Use dsolve to obtain solution
sol1 = sp.dsolve(eq1, P(t)) # Without initial condition
x
display(sol1)

In [ ]:
#Define initial conditions and parameters
P0 = 0.1
a = [1.8, 2.0, 2.5, 3.5, 3.8, 4.0]

#For iteration
Pvals = []
tVals = []

#Define X and t using different values of sigdt
for i in a:
    t = np.arange(0, 40+i, i)
    P = np.zeros(len(t))
    P[0] = P0
    #Euler method calculation
    for n in range(0,len(P)-1):
        P[n+1] = P[n] + i*P[n]*(1-P[n])
    #Add t-X values to iteration lists
    Pvals.append(P)
    tVals.append(t)

plt.figure(figsize=(9,6))
for i in range(0, len(Pvals)):
    plt.subplot(2,3,i+1)
    plt.plot(tVals[i], Pvals[i], label=f'{a[i]}')
    plt.legend()
    plt.grid()

plt.tight_layout()
plt.show()

In [ ]:
def sig(x):
    return 1/(1+np.exp(-x))

r1 = np.linspace(0,5,100)
r2 = np.linspace(-5,5,100)
title1 = r'Graph of $\sigma$ = $\frac{1}{1+e^{-x}}$'
plt.title(title1, size=10)
plt.plot(r1, sig(r1))
plt.grid()
plt.show()

In [ ]:
def softmax(x):
    exp_x = np.exp(x)
    return exp_x/exp_x.sum()

def softmax_loop(x):
    #Create array same length as x
    sigma = np.arange(0.0,len(x))
    #Sum variable
    exp_sum = 0
    for i in range(0, len(x)):
        #Find e^x_i
        exp_x = np.exp(x[i])
        #Add e^x_i to sum 
        exp_sum += exp_x
        #Store sigma(x)_i
        sigma[i] = exp_x/exp_sum
    return sigma
    
#Example input vector
input_vector = np.array([10, 2.0, 0.1])

#Applying softmax
output_vector = softmax(input_vector)
output_vector2 = softmax_loop(input_vector)
#Displaying results
print("Input Vector:", input_vector)
print("Softmax Output:\n", output_vector)
print('Softmax_loop Output:\n', output_vector2)
#Compare values
print('Difference of Softmax and Softmax_loop functions for each value of x:\n', (output_vector2-output_vector))

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

#Define parameters
dt = 0.001
t = np.arange(0,10+dt,dt)
sigma = 0.2
y0 = 0.01
#Create function array that is same size as domain
y = np.zeros(len(t)) #Will add correct values
#Initial condition
y[0] = y0

#Calculate values of y using Euler method
for i in range(0, len(y)-1):
    #Approximation formula
    y[i+1] = y[i] + dt*(sigma*y[i])

#Generate plot
plt.plot(t, y, 'k', linewidth=3)
plt.plot(t, y0*np.exp(sigma*t), '--', color='orange')
plt.legend(['Numerical Solution', 'Analytical Solution'])
plt.title(r'Numerical and Analytical Solution for DE: $\frac{dy}{dt} = \sigma t$')
plt.ylabel('y(t)')
plt.xlabel('t')
plt.grid()
plt.show()

### References
Lorenz, 1964: The Problem of Deducing the Climate from the Governing Equations. Massachusetts Institute of Technology. 2024\
May, 1976: Simple Mathematical Models With Very Complicated Dynamics. University of Oxford. 2024.\
Verdugo, 2024: Report on Homework Assignments 3, 5, 9, 10. Math 340 Programming in Mathematics. San Diego State University. 2024